### ISSUE TITLE
Running against non-default aws profiles

### ISSUE THREAD

**Issue by jqtrde** [anandthakker/here-spot#1]
_First off, just wanted to mention that this is awesome_ :clap: 

Would it be possible to run `here-spot` against a non-default aws profile?

In the case of the `awscli` tools, you can do that via:

``` bash
aws s3 ls --profile=personal
```

Being able to do the same with `here-spot` would be great for working across aws accounts on the same machine.

Thanks again!

**Comment by anandthakker** [comment]
Answering from phone so I can't check at the moment, but I _think_ you can
do:

AWS_PROFILE=personal here-spot ...

**Comment by jqtrde** [comment]
:pray: yaaasss!
